logging:
  level:
    com.backbase: DEBUG

server:
  port: 9999

eureka:
  client:
    enabled: false

mastercard:
  mcob:
    ais:
      api:
        base-uri: https://developer.mastercard.com/apigwproxy/openbanking/connect/api
